### ISSUE TITLE
Titan is resetting TargetFrame position

### ISSUE THREAD

**Issue by Leah-UK** [haggen/wow#54]
Hey! I love the idea of this addon, saves me from major OCD.. However, for some reason after closing focus on a target the frame resets to the top of the screen. My own player target is completely fine. Am I doing something wrong?

Thanks!

**Comment by haggen** [comment]
Hi! Thanks for getting in touch.

Just to be sure, you're experiencing this on Retail or Classic?

Either way, you're doing anything wrong. Could elaborate more on what you mean by "closing focus on a target"? That would help me pinpoint where the issue could be.

**Comment by Leah-UK** [comment]
Hey :) on Classic.
I click on my nameplate (frame thingy) and then unlock it.. move it and the targetted frame correctly mirrors. However once i close my target (by pressing Escape) and click on my target again the targeted frame is at the top of my screen. EDIT: < top of my screen in the default pos

**Comment by Leah-UK** [comment]
So it looks like this issue is caused by Titan Panel :S

**Comment by haggen** [comment]
That was going to be my next question, but since you went ahead the checked I can start looking into it. :)

Thanks again for the report and I hope to have a fix as soon as possible.

**Comment by haggen** [comment]
I opened a ticket over on TItan's tracker https://sourceforge.net/p/titan-panel-classic/tickets/21/

**Comment by Leah-UK** [comment]
Cool, the only reason I use Titan Panel is for the repair cost display. Will just disable it for now and use this addon instead.

**Comment by Leah-UK** [comment]
Hey, btw my friend is asking for this on retail. Ever plan on moving it over?

**Comment by haggen** [comment]
@Leah-UK I actually have a version for retail but it hasn't been updated for some time. In any case, I'm pretty sure if you just copy the classic version over to retail add-ons directory it'll work just fine. Let me know how it goes!

**Comment by Leah-UK** [comment]
Hey @haggen I forgot to reply. Copying it over to retail has been completely fine so far.

**Comment by haggen** [comment]
Wonderful! 😎️
