### ISSUE TITLE
Locking

### ISSUE THREAD

**Issue by Herdna** [haggen/wow#78]
Everytime i log on i have to Lock the ui because its allwasy unlocked for some reason.

**Comment by waytoomuchgaming** [comment]
Same problem here. Each relog unlock the frames.

**Comment by Ansi** [comment]
And my axe

**Comment by haggen** [comment]
@Herdna @waytoomuchgaming @Ansi If you all are still interested (sorry for the delay) this add-on has been rebranded as [Tunnelvision](https://github.com/haggen/wow/releases/tag/classic/Tunnelvision/1.0.0) and the issue of unlocking is now fixed. :)

Retail version still have to be updated though.
