### ISSUE TITLE
Make the positions/lock/buffs position account wide

### ISSUE THREAD

**Issue by waytoomuchgaming** [haggen/wow#86]
That one pixel diff with every different character triggers me ^^

**Comment by haggen** [comment]
Would profiles solve this for you? I'm thinking every character you log with the add-on enabled generates a profile that is updated automatically when you drag the frames. Then from the Interface settings menu you could load the profile from another character and have the same positioning.

**Comment by waytoomuchgaming** [comment]
> Would profiles solve this for you?

Yes, i suppose if i can use the same "default" profile for everybody, i'll be fine with that.

**Comment by haggen** [comment]
Great! Then I'll track that on #84 and I'll close this one to avoid confusion.
